version: '3'

services:
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: /run/secrets/db_root_username
      MONGO_INITDB_ROOT_PASSWORD: /run/secrets/db_root_password
    secrets:
      - db_root_password
      - db_root_username
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
  menu_display:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGO_PORT: 27017:27017
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ${PWD}:/opt/code
secrets:
   db_root_username:
     file: db_root_username.txt
   db_root_password:
     file: db_root_password.txt
volumes:
    mongodbdata: