version: '3.8'

services:
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/db_root_username
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
    secrets:
      - db_root_username
      - db_root_password
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
  web:
    build:
      context: ${PWD}
      dockerfile: Dockerfile
    environment:
      MONGO_PORT: 27017:27017
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ${PWD}:/opt/code
secrets:
    db_root_username:
      file: db_root_username.txt
    db_root_password:
      file: db_root_password.txt
volumes:
  mongodbdata: