# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x15\n\x07OrderID\x12\n\n\x02id\x18\x01 \x01(\t\")\n\x04Item\x12\x0f\n\x07product\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"\xa4\x01\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x05items\x18\x02 \x03(\x0b\x32\x05.Item\x12\x0e\n\x06status\x18\x03 \x01(\t\x12+\n\x07\x63reated\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x13\n\x0b\x63ustomer_id\x18\x05 \x01(\t\x12\x12\n\nkitchen_id\x18\x06 \x01(\t\x12\x13\n\x0b\x64\x65livery_id\x18\x07 \x01(\t\" \n\x06Orders\x12\x16\n\x06orders\x18\x01 \x03(\x0b\x32\x06.Order2\xdb\x01\n\x0cOrderService\x12,\n\tGetOrders\x12\x16.google.protobuf.Empty\x1a\x07.Orders\x12\x1d\n\x0b\x43reateOrder\x12\x06.Order\x1a\x06.Order\x12\x1c\n\x08GetOrder\x12\x08.OrderID\x1a\x06.Order\x12/\n\x0b\x43\x61ncelOrder\x12\x08.OrderID\x1a\x16.google.protobuf.Empty\x12/\n\x0b\x44\x65leteOrder\x12\x08.OrderID\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERID']._serialized_start=77
  _globals['_ORDERID']._serialized_end=98
  _globals['_ITEM']._serialized_start=100
  _globals['_ITEM']._serialized_end=141
  _globals['_ORDER']._serialized_start=144
  _globals['_ORDER']._serialized_end=308
  _globals['_ORDERS']._serialized_start=310
  _globals['_ORDERS']._serialized_end=342
  _globals['_ORDERSERVICE']._serialized_start=345
  _globals['_ORDERSERVICE']._serialized_end=564
# @@protoc_insertion_point(module_scope)
