apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: mongodb
  namespace: default
spec:
  destination:
    name: mongodb
  sources:
    - name: menuu
      action: allow