global:
  name: consul
  datacenter: kubernetes
 
server:
  replicas: 1
 
client:
  enabled: true
 
connectInject:
  enabled: true
 
ui:
  enabled: true
  service:
    type: LoadBalancer
 
controller:
  enabled: true