apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: kong-to-ui
spec:
  destination:
    name: ui
  sources:
    - name: external-kong-proxy
      permissions:
        - action: allow
          http:
            pathExact: /
            methods: ['GET']
        - action: allow
          http:
            pathPrefix: /ui
            methods: ['GET']