# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\".\n\x0b\x41uthRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1d\n\x0cTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"]\n\x0c\x41uthResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x03 \x01(\t\x12\x15\n\rrefresh_token\x18\x04 \x01(\t\"/\n\rTokenResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x96\x01\n\x0b\x41uthService\x12+\n\x0c\x41uthenticate\x12\x0c.AuthRequest\x1a\r.AuthResponse\x12,\n\x0cRefreshToken\x12\r.TokenRequest\x1a\r.AuthResponse\x12,\n\x0bVerifyToken\x12\r.TokenRequest\x1a\x0e.TokenResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHREQUEST']._serialized_start=14
  _globals['_AUTHREQUEST']._serialized_end=60
  _globals['_TOKENREQUEST']._serialized_start=62
  _globals['_TOKENREQUEST']._serialized_end=91
  _globals['_AUTHRESPONSE']._serialized_start=93
  _globals['_AUTHRESPONSE']._serialized_end=186
  _globals['_TOKENRESPONSE']._serialized_start=188
  _globals['_TOKENRESPONSE']._serialized_end=235
  _globals['_AUTHSERVICE']._serialized_start=238
  _globals['_AUTHSERVICE']._serialized_end=388
# @@protoc_insertion_point(module_scope)
