apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: api-gateway
# Allow traffic from api-gateway to menu
spec:
  destination:
    name: menu
  sources:
    - name: api-gateway
      action: allow