apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: nginx-menu
# Allow traffic from api-gateway to menu
spec:
  destination:
    name: menu
  sources:
    - name: nginx
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
 name: mongodb
 namespace: default
# Allow traffic from menuu to mongodb
spec:
 destination:
   name: mongodb
 sources:
   - name: menu
     action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
 name: cache-redis
 namespace: default
# Allow traffic from menuu to redis
spec:
 destination:
   name: cache-redis
 sources:
   - name: menu
     action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
 name: menu-config-mongodb
 namespace: default
# Allow traffic from menu-config to mongodb-config
spec:
 destination:
   name: menu-config-mongodb
 sources:
   - name: menuconfig
     action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: nginx-menu-config
# Allow traffic from api-gateway to menu-config
spec:
  destination:
    name: menuconfig
  sources:
    - name: nginx
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: api-gateway-nginx
# Allow traffic from api-gateway to menu
spec:
  destination:
    name: nginx
  sources:
    - name: api-gateway
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
 name: apis-rabbitmq
 namespace: default
spec:
 destination:
   name: rabbitmq
 sources:
   - name: menuconfig
     action: allow
   - name: menu
     action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
 name: auth-postgresql
 namespace: default
spec:
 destination:
   name: postgres
 sources:
   - name: auth
     action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
 name: menuconfig-auth
 namespace: default
spec:
 destination:
   name: auth
 sources:
   - name: menuconfig
     action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
 name: nginx-order
 namespace: default
spec:
 destination:
   name: order
 sources:
   - name: nginx
     action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
 name: order-mongodb
 namespace: default
spec:
 destination:
   name: order-mongodb
 sources:
   - name: order
     action: allow