apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: api-gateway
# Allow traffic from api-gateway to menu
spec:
  destination:
    name: menu
  sources:
    - name: api-gateway
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
 name: mongodb
 namespace: default
# Allow traffic from menuu to mongodb
spec:
 destination:
   name: mongodb
 sources:
   - name: menu
     action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
 name: cache-redis
 namespace: default
# Allow traffic from menuu to redis
spec:
 destination:
   name: cache-redis
 sources:
   - name: menu
     action: allow