apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: menu
  namespace: default
spec:
  protocol: "http"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: menu
  namespace: default
automountServiceAccountToken: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: menu
  name: menu
spec:
  type: ClusterIP
  ports:
    - port: 1027
      targetPort: 1027
  selector:
    app: menu
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu
  namespace: default
  labels:
    app: menu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menu
  template:
    metadata:
      labels:
        app: menu
        service: menu
      annotations:
        consul.hashicorp.com/connect-inject: "true"
    spec:
      serviceAccountName: menu
      containers:
        - name: menu
          image: "opielapatryk/menu_display_eks"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1027
          env:
            - name: MONGO_HOST
              value: "mongodb"
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: REDIS
              value: "cache-redis"