apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: menu
  namespace: default
spec:
  protocol: "http"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: menu
  namespace: default
automountServiceAccountToken: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: menu
  name: menu
spec:
  type: ClusterIP
  ports:
    - port: 1027
      targetPort: 1027
  selector:
    app: menu
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu
  namespace: default
  labels:
    app: menu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menu
  template:
    metadata:
      labels:
        app: menu
        service: menu
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-upstreams: "mongodb:27017,cache-redis:6379,rabbitmq:5672"
    spec:
      serviceAccountName: menu
      containers:
        - name: menu
          image: "opielapatryk/menu_display:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1027