apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: menuconfig
  namespace: default
spec:
  protocol: "http"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: menuconfig
  namespace: default
automountServiceAccountToken: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: menuconfig
  name: menuconfig
spec:
  type: ClusterIP
  ports:
    - port: 1028
      targetPort: 1028
  selector:
    app: menuconfig
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: menuconfig
  namespace: default
  labels:
    app: menuconfig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menuconfig
  template:
    metadata:
      labels:
        app: menuconfig
        service: menuconfig
      annotations:
        consul.hashicorp.com/connect-inject: "true"
    spec:
      serviceAccountName: menuconfig
      containers:
        - name: menuconfig
          image: "opielapatryk/menu_config_eks2"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1028
          env:
            - name: MONGO_HOST
              value: "menu-config-mongodb"
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: AUTH_GRPC
              value: "auth"