global:
  enabled: true
  name: consul
  image: hashicorp/consul:1.16.0
  datacenter: dc1
  tls:
    enabled: true
  acls:
    manageSystemACLs: true
  metrics:
    enabled: true
    enableAgentMetrics: true
    agentMetricsRetentionTime: "1m"
server:
  enabled: true
  replicas: 1
ui:
  enabled: true
  service:
    type: NodePort
  metrics:
    enabled: true
    provider: "prometheus"
    baseURL: http://prometheus-server.default.svc.cluster.local
connectInject:
  enabled: true
  metrics:
    defaultEnabled: true
    defaultEnableMerging: true
  apiGateway:
    managedGatewayClass:
      serviceType: LoadBalancer
      useHostPorts: true