global:
  enabled: true
  name: consul
  image: hashicorp/consul:1.16.0
  datacenter: dc1
  tls:
    enabled: true
  acls:
    manageSystemACLs: true
server:
  enabled: true
  replicas: 1
connectInject:
  enabled: true
  apiGateway:
    managedGatewayClass:
      serviceType: LoadBalancer
      useHostPorts: true